# bansal
# CrimeSync Multi-Dialect Forensic OCR & Document NLP Extraction Engine (Tesseract + TrOCR PyTorch)
# Author: Rajesh Bansal

FROM python:3.11-slim

# bansal
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-hin \
    tesseract-ocr-mar \
    tesseract-ocr-ben \
    libgl1-mesa-glx \
    libglib2.0-0 \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir \
    pytesseract \
    pdf2image \
    transformers \
    torch \
    fastapi \
    uvicorn \
    pillow

EXPOSE 8085

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8085"]
