// CrimeSync Indian Law Enforcement Cases Dataset (Fail-Safe & Reactive)
export interface LawCase {
  id: string;
  fir_number: string;
  title: string;
  description: string;
  crime_category: string;
  priority: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  status: 'INVESTIGATING' | 'OPEN' | 'UNDER_REVIEW' | 'CLOSED';
  jurisdiction_city: string;
  lead_investigator_name: string;
  badge_number: string;
  department: string;
  lead_suspect: string;
  lead_suspect_role: string;
  tracked_money_inr: number;
  evidence_count: number;
  suspects_count: number;
  isCompromised?: boolean;
}

export const ALL_CASES: LawCase[] = [
  {
    id: 'CRS-2026-HNY-047',
    fir_number: 'FIR/CHE/2026/0947',
    title: 'Operation Maya: Synthetic Identity Ingestion (satyakiran)',
    description: 'Fabricated FIR dossier for satyakiran generated via recursive LLM hallucination and injected into police records. Kinematic transit impossibilities, Aadhaar biometric hash collision, and CDR cell tower triangulation mismatch detected.',
    crime_category: 'DECEPTIVE_FIR',
    priority: 'CRITICAL',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Chennai & Hyderabad',
    lead_investigator_name: 'ACP Devendra Singhania',
    badge_number: 'CHE-CYB-0947',
    department: 'Special Cyber Crime & Counter-Deception Unit',
    lead_suspect: 'satyakiran "Phantom" Sen',
    lead_suspect_role: 'Synthetic Identity Operator',
    tracked_money_inr: 8750000,
    evidence_count: 3,
    suspects_count: 1,
    isCompromised: true,
  },
  {
    id: 'CASE-2026-004',
    fir_number: 'FIR/KOL/2026/0412',
    title: 'Operation Chakra: Tech Support & Crypto Scam',
    description: 'Illicit VOIP call center ring masquerading as global tech support, coercing wire transfers into Indian mule accounts and OTC USDT channels.',
    crime_category: 'FINANCIAL_FRAUD',
    priority: 'CRITICAL',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Kolkata & Noida',
    lead_investigator_name: 'Superintendent Ananya Sengupta',
    badge_number: 'CBI-HQ-0012',
    department: 'Anti-Corruption & Economic Offences',
    lead_suspect: 'Anirban Mukherjee (Alias: Bobby)',
    lead_suspect_role: 'Call Center Kingpin',
    tracked_money_inr: 4130000,
    evidence_count: 2,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-005',
    fir_number: 'FIR/MUM/2026/1842',
    title: 'Operation Vajra: Digital Arrest & Fake CBI Extortion',
    description: 'Syndicate impersonating CBI & ED officers on Skype/WhatsApp, placing victims under 72-hour virtual house arrest to extort crores.',
    crime_category: 'ORGANIZED_SYNDICATE',
    priority: 'CRITICAL',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Mumbai & Jaipur',
    lead_investigator_name: 'Inspector Priya Kulkarni',
    badge_number: 'MUM-CYB-4091',
    department: 'Cyber Crime Investigation Cell',
    lead_suspect: 'Kunwar Pratap Singh (Alias: Rana Saheb)',
    lead_suspect_role: 'Digital Arrest Ring Leader',
    tracked_money_inr: 5150000,
    evidence_count: 2,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-006',
    fir_number: 'FIR/AHM/2026/0593',
    title: 'Operation Durg: Biometric & AePS Micro-ATM Bypass',
    description: 'High-precision silicone fingerprint casting from public land deed registries used to execute unauthorized AePS micro-ATM withdrawals.',
    crime_category: 'IDENTITY_THEFT',
    priority: 'HIGH',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Ahmedabad & Surat',
    lead_investigator_name: 'SI Vikramaditya Reddy',
    badge_number: 'HYD-CID-7740',
    department: 'CID Financial Fraud Division',
    lead_suspect: 'Jignesh Patel (Alias: Silicon Master)',
    lead_suspect_role: 'Biometric Cloner & AePS Hacker',
    tracked_money_inr: 1960000,
    evidence_count: 2,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-007',
    fir_number: 'FIR/BLR/2026/0778',
    title: 'Operation Netra: AI Deepfake Video Extortion',
    description: 'Generative diffusion models used to fabricate high-ranking corporate executive compromising videos for Monero and USDT extortion.',
    crime_category: 'CYBER_ATTACK',
    priority: 'HIGH',
    status: 'OPEN',
    jurisdiction_city: 'Bengaluru & Gurugram',
    lead_investigator_name: 'DSP Arvind Swaminathan',
    badge_number: 'BLR-INT-1102',
    department: 'Forensic Science Laboratory (FSL)',
    lead_suspect: 'Kavita Nair (Alias: Aria)',
    lead_suspect_role: 'AI Deepfake Synthesizer',
    tracked_money_inr: 2550000,
    evidence_count: 2,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-008',
    fir_number: 'FIR/PUN/2026/1129',
    title: 'Operation Kuber: Instant Loan App & Hawala Funnel',
    description: 'Malicious Android APKs stealing contacts/photos, backed by aggressive harassment call centers and automated Hawala money laundering.',
    crime_category: 'FINANCIAL_FRAUD',
    priority: 'CRITICAL',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Pune & Hyderabad',
    lead_investigator_name: 'ACP Rajeshwar Sharma',
    badge_number: 'DEL-IPS-8821',
    department: 'Special Cell / Cyber Crime Unit',
    lead_suspect: 'Chirag Mehta (Alias: Charlie)',
    lead_suspect_role: 'Hawala Settlement Broker',
    tracked_money_inr: 6280000,
    evidence_count: 2,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-009',
    fir_number: 'FIR/CHE/2026/0204',
    title: 'Operation Rudra: Power Grid SCADA Ransomware',
    description: 'Targeted zero-day VPN exploitation attempting unauthorized command injection into Southern Regional Power Grid SCADA relays.',
    crime_category: 'CYBER_ATTACK',
    priority: 'CRITICAL',
    status: 'OPEN',
    jurisdiction_city: 'Chennai & New Delhi',
    lead_investigator_name: 'Inspector Priya Kulkarni',
    badge_number: 'MUM-CYB-4091',
    department: 'Cyber Crime Investigation Cell',
    lead_suspect: 'Karthik Ramanathan (Alias: GhostByte)',
    lead_suspect_role: 'APT Exploit Developer',
    tracked_money_inr: 10000000,
    evidence_count: 2,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-001',
    fir_number: 'FIR/DEL/2026/0891',
    title: 'Operation Trishul: Hawala & Phishing Syndicate',
    description: 'Large-scale identity theft and mule bank account network targeting PSU bank customers in NCR and MMR region.',
    crime_category: 'FINANCIAL_FRAUD',
    priority: 'CRITICAL',
    status: 'INVESTIGATING',
    jurisdiction_city: 'New Delhi & Mumbai',
    lead_investigator_name: 'ACP Rajeshwar Sharma',
    badge_number: 'DEL-IPS-8821',
    department: 'Special Cell / Cyber Crime Unit',
    lead_suspect: 'Vikramaditya Shinde (Alias: Vicky Bhai)',
    lead_suspect_role: 'Syndicate Kingpin',
    tracked_money_inr: 3480000,
    evidence_count: 2,
    suspects_count: 3,
  },
  {
    id: 'CASE-2026-002',
    fir_number: 'FIR/MUM/2026/1044',
    title: 'GridShield: Cyber Attack on Power Distribution',
    description: 'Targeted spear-phishing and C2 beaconing detected attempting lateral movement into SCADA systems.',
    crime_category: 'CYBER_ATTACK',
    priority: 'CRITICAL',
    status: 'OPEN',
    jurisdiction_city: 'Mumbai',
    lead_investigator_name: 'Inspector Priya Kulkarni',
    badge_number: 'MUM-CYB-4091',
    department: 'Cyber Crime Investigation Cell',
    lead_suspect: 'Meera Krishnan (Alias: ByteQueen)',
    lead_suspect_role: 'Malware Developer & C2 Handler',
    tracked_money_inr: 0,
    evidence_count: 1,
    suspects_count: 1,
  },
  {
    id: 'CASE-2026-003',
    fir_number: 'FIR/BLR/2026/0332',
    title: 'Operation Garud: Fake Electricity Bill Scam & SIM OTP Ring',
    description: 'Bengaluru resident K. Subramanian (63) tricked by fake BESCOM disconnection SMS into installing OTP-stealing malware (BESCOM-Pay.apk). ₹1,80,000 drained via UPI and cashed out at Indiranagar ATM within 50 minutes. Suspect: Sunil Yadav, SIM card shop owner operating 200+ fraudulent SIMs with forged Aadhaar cards.',
    crime_category: 'ORGANIZED_SYNDICATE',
    priority: 'HIGH',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Bengaluru',
    lead_investigator_name: 'DSP Arvind Swaminathan',
    badge_number: 'BLR-INT-1102',
    department: 'Forensic Science Laboratory (FSL)',
    lead_suspect: 'Sunil Yadav (Alias: Sunny / BESCOM Officer Ravi)',
    lead_suspect_role: 'SIM Farm Operator & OTP Ring Leader',
    tracked_money_inr: 180000,
    evidence_count: 7,
    suspects_count: 2,
  },
  {
    id: 'CASE-2026-010',
    fir_number: 'FIR/BLR/2026/0910',
    title: 'Operation Task Trap: Fake YouTube Like Job Scam',
    description: 'College student Pooja (21, Bengaluru) defrauded of ₹5,00,000 via a fake "earn by liking YouTube videos" Telegram scam. Kingpin Rohit Verma (Mewat) traced via IMEI cross-case match to Jamtara FIR/2024/0882. Money mules Amit Kumar (Canara Bank) & Rahul Sharma (ICICI Bank) used to layer funds. ₹1,80,000 cashed out at Jaipur ATM — mule face identified from CCTV.',
    crime_category: 'FINANCIAL_FRAUD',
    priority: 'HIGH',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Bengaluru & Jaipur',
    lead_investigator_name: 'Inspector Priya Kulkarni',
    badge_number: 'MUM-CYB-4091',
    department: 'Cyber Crime Investigation Cell',
    lead_suspect: 'Rohit Verma (Alias: @crypto_tasks_admin / Ricky Boss)',
    lead_suspect_role: 'Telegram Scam Syndicate Kingpin',
    tracked_money_inr: 500000,
    evidence_count: 5,
    suspects_count: 3,
  },
  {
    id: 'CASE-2026-011',
    fir_number: 'FIR/HYD/2026/1842',
    title: 'Operation Parcel Trap: FedEx Digital Arrest Scam',
    description: 'Dr. Aruna Rao (58, Hyderabad) extorted of ₹10,00,000 via fake FedEx robocall & 6-hour Skype "Digital Arrest". Kingpin Vikram Gurjar (Bharatpur) traced via VoIP voiceprint. ₹6L frozen at HDFC Ahmedabad; ₹3.6L ATM cash-out in Surat; 97.1% CCTV face match on mule Mukesh Solanki.',
    crime_category: 'ORGANIZED_SYNDICATE',
    priority: 'CRITICAL',
    status: 'INVESTIGATING',
    jurisdiction_city: 'Hyderabad & Surat',
    lead_investigator_name: 'DSP Arvind Swaminathan',
    badge_number: 'BLR-INT-1102',
    department: 'CID Cyber Crime Division',
    lead_suspect: 'Vikram Gurjar (Alias: "DCP Rathore")',
    lead_suspect_role: 'Digital Arrest Syndicate Kingpin',
    tracked_money_inr: 1000000,
    evidence_count: 5,
    suspects_count: 3,
  },
];

export function getCaseById(id: string): LawCase {
  return ALL_CASES.find((c) => c.id === id) || ALL_CASES[0];
}
